[package]
name = "spraycc"
version = "0.1.0"
authors = ["Jason McCampbell <jasonmccampbell@gmail.com>"]
edition = "2018"

[dependencies]
# TODO: Reduce feature set
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3", features = ["codec"] }
bytes = "0.5"
clap = "2"
tempdir = "0.3"
nix = "0.14"
serde = { version = "1", features = ["derive"] }
bincode = "1"
byteorder = "1"
gethostname = "0"
libc = "0.2"
toml = "0.5"
which = "2"
