
# Executor options
[exec]
# Number of executors to start initially
initial_count = 5
# Maximum number of executors to keep running at one. Set to 'initial_count' to have all submitted at once.
max_count = 200
# Number of submitted, but not yet connected executors. This plus submit delays determins how fast the
# cloud of executors increases fron initial_count to max_count.
keep_pending = 3
# Delay from last submitted task until idle executors are released
release_delay = 30
# Shutdown after idle for N seconds
idle_shutdown_after = 60
# Command used to start new executors. Options such as --callme will be appended.
start_cmd = "bsub -q linux -n 1 -W 1:0 /tools/bin/spraycc"

# Alternate start command invoked by --alt option, useful for selecting a
# different queue or completely different submit command
alt_start_cmd = "/tools/bin/submit_job /tools/bin/spraycc"
